FROM offsite/os15-php8-base-dev-debug:latest

VOLUME /host
VOLUME /var/log/applications
VOLUME /var/log/apache2

COPY etc/php/conf.d/*.ini /etc/php8/conf.d/
COPY scripts/*.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/*.sh

RUN printf "\n/usr/local/bin/pre_start_local.sh\n" >> /usr/local/bin/pre_start.sh;

ENTRYPOINT ["/usr/local/bin/start.sh"]